### ISSUE TITLE
버튼 안의 span 요소가 transition이 안먹는 문제

### ISSUE THREAD

**Issue by blueprint-12** [blueprint-12/javascript-practice-2021#1]
button요소에 content가 있고 span태그로 감싸진 ">" arrow text 가 있습니다.
버튼에 마우스를 올렸을 시, 해당 arrow text만 오른쪽으로 20px정도 움직임을 주고싶은데
정확히 span요소 마우스를 올리지않으면 transition이 동작하지 않습니다. 
button에도 transition: all 속성을 주어 내부에 작동하는 transition을 감지할 수 있을 줄 알았는데 원하는대로 동작하지 않음 

```CSS 
.mainMenu__register-btn {
  width: 100%;
  color: white;
  margin-top: 7px;
  display: block;
  background-color: black;
  padding: 7px 10px;
  text-align: left;
  transition: all 0.2s ease-in-out;
}
.mainMenu__register-btn:hover {
  color: black;
  background-color: white;
  border: 1px solid black;
}
#arrow {
  display: inline-block;
  transition: transform 0.2s ease-in-out;
}
#arrow:hover {
  transform: translateX(20px);
}
```

**Comment by blueprint-12** [comment]
<b>문제 상황</b>:  정확히 span요소 마우스를 올리지않으면 transition이 동작하지 않습니다. 
제가 원하는 동작 방식은 부모인 button에 hover됐을 시 span요소가 움직이는 것입니다. 
```css
#arrow:hover {
  transform: translateX(20px);
}
``` 
위의 코드를 보면 arrow라는 id를 가진 span요소가 hover 됐을 때이니 당연히 해당 요소에서만 동작합니다.  
```css
.mainMenu__register-btn:hover #arrow {
  transform: translateX(50px);
}
```
위 처럼 부모 요소가 hover됐을 때, 그 내부에 arrow 아이디를 가진 span 요소에 transform을 주면 해결됩니다.

가상클래스 요소가 꼭 내가 변경하고 싶은 HTML요소에 붙는 것이 아니라 부모 container 요소라면 해당 요소에게 주어도 됩니다.
